Feature/weni apps support
Ilhasoft/rapidpro pull request #173
Opened 2021-02-04 18:15 UTC by jcbalmeida

Adds support to Weni's rapidpro-apps package:

- Adds weni apps into INSTALLED_APPS
- Adds rapidpro-apps installation to Dockerfile

2021-02-05 17:24 UTC, paulobernardoaf approved these changes

2021-02-10 14:00 UTC, matmsa27 requested changes
Why have .po files on this PR? If we do this, probably we will lose the translations we have in production. See that pls: https://github.com/rapidpro/rapidpro/issues/1417
My suggestion is on push still the .po that we have in production for to do not have problems.

2021-02-10 18:25 UTC, jcbalmeida commented
> Why have .po files on this PR? If we do this, probably we will lose the translations we have in production. See that pls: [rapidpro#1417](https://github.com/rapidpro/rapidpro/issues/1417)
> My suggestion is on push still the .po that we have in production for to do not have problems.

Messages updated:
 - pt_BR translated checked-out from update-master-rp/6.1.4-weni-hotjar (currently in production) and fixed with poedit
 - Other languages updated from v6.1.4

2021-02-10 19:42 UTC, matmsa27 approved these changes

2021-02-10 23:03 UTC, merged