Add pages_read_engagement permission for Instagram
Ilhasoft/rapidpro pull request #271
Opened 2022-02-24 15:46 UTC by Robi9

2022-02-24 21:14 UTC, matmsa27 requested changes

2022-02-24 21:14 UTC, matmsa27 commented on templates/channels/types/instagram/refresh_token.haml
>      });
Please, add a endline blank here

2022-02-25 13:02 UTC, paulobernardoaf approved these changes

2022-02-25 14:34 UTC, matmsa27 approved these changes

2022-02-25 14:34 UTC, merged