Fix: back button history behavior
Ilhasoft/rapidpro pull request #272
Opened 2022-02-24 18:37 UTC by paulobernardoaf

2022-02-24 19:25 UTC, matmsa27 requested changes

2022-02-24 19:25 UTC, matmsa27 commented on templates/weni/side.haml
>      }
missing endline here

2022-02-24 21:36 UTC, matheusm approved these changes

2022-02-25 14:33 UTC, matmsa27 approved these changes

2022-02-25 14:34 UTC, merged